### ISSUE TITLE
Babble-Zone-2.2 Missing

### ISSUE THREAD

**Issue by koyashi** [Aviana/HealComm#11]
When I load the addon it gives an error on line 24 of the /libs/Healcomm-1.0/HealComm-1.0.lua file saying "Cannot find a library instance of Babble-Zone-2.2"

![healcomm error](https://user-images.githubusercontent.com/7952227/32912675-af7d9496-cb07-11e7-8822-4f9d1c785379.JPG)

And the line on that file is:

local BZ = AceLibrary("Babble-Zone-2.2")

"Babble-Zone-2.2" doesn't exist on the /libs folder

Not sure if this is the problem.
Hope it helps

**Comment by Aviana** [comment]
Fixed in master. Will make a new release for it soon.
