### ISSUE TITLE
"Translation "Nature Aligned" does not exist" 

### ISSUE THREAD

**Issue by kodikun** [Aviana/HealComm#12]
I get this error upon login: 
![ss 2017-11-16 at 11 30 25](https://user-images.githubusercontent.com/1770645/32929510-788eebb4-cb26-11e7-86e4-30214933decb.jpg)

**Comment by Road-block** [comment]
This is another instance of the Babble-Spell-2.2 loaded by HealComm being discarded by AceLibrary for another instance of the library with the same or higher minor revision number.

**Comment by kodikun** [comment]
Searching through it seems that BigWigs, Cartographer, MSBT, and DPSMate all have the Babble-Spell library. The DPSMate version is marked as 2.3 and the rest are 2.2.  If I disable these addons, I instead get this error: 
![ss 2017-11-17 at 12 55 06](https://user-images.githubusercontent.com/1770645/32961456-9b72991c-cb96-11e7-870e-b061b5941ac1.jpg)

**Comment by Road-block** [comment]
That second error will be fixed if you download the most recent HealComm, but the first one not, as long as there's another Babble-Spell-2.2 taking precedence from another addon.

**Comment by Aviana** [comment]
Bumped lib versions ridiculously.
