### ISSUE TITLE
Shaman heals aren't being tracked

### ISSUE THREAD

**Issue by Zykes** [Aviana/HealComm#15]
All of the Shaman heals aren't predicted by the addon. Been in several groups on a 1.12.1 client (Kronos 3) and as a warlock I use HealComm to know when I should life tap, but Shaman heals never show a predicted heal even though they're definitely targeting and healing me (even with single target heals)

**Comment by Aviana** [comment]
Pretty sure that something that obvious isn't broken. Downloaded the newest version? Which UF are you using?
