### ISSUE TITLE
Separate repo for LCHC

### ISSUE THREAD

**Issue by d87** [Aviana/HealComm#16]
Hey, will you make a separate repo for your LibHealComm port for embedding? And is it completed?

**Comment by Aviana** [comment]
Final testing remains as there were literally only 40 people online during the last days of beta. I am hoping for the last stress test to validate the actual comm part. Locally it already works fine.

I will look into making a separate repo for lchc after i have confirmed basic functionality.

**Comment by Aviana** [comment]
https://github.com/Aviana/LibClassicHealComm-1.0
