### ISSUE TITLE
Healcomm not communicating

### ISSUE THREAD

**Issue by Vilpone** [Aviana/HealComm#17]
Hey. Just tested this out on the stress test.

The addon shows predicted heals cast by myself, but doesnt show any heals that others are casting in my party.

**Comment by Slyvampy** [comment]
Yeah works fine on a healer, but the rest of the group have the addon but do not show. Also does not show things like renew.

**Comment by Vypoxia** [comment]
I can confirm the problem from Vilpone. We were two healers in the group, so I can not confirm Slyvampy.

**Comment by Aviana** [comment]
Should be fixed in the latest commit.
