### ISSUE TITLE
Error in German Localization

### ISSUE THREAD

**Issue by Z1mmey** [Aviana/HealComm#2]
Hi, thanks for your work!

I noticed an error in the German localization of some priest skills. "Lesser Heal" and "Heal" are incorrectly translated as "Geringe Heilung" and "Heilung", while they should be "Geringes Heilen" and "Heilen" respectively.

For some reason, the translation "Große Heilung" for "Greater Heal" is correct though.

Greetings!

**Comment by Aviana** [comment]
Fixed.
