### ISSUE TITLE
bad argument #5

### ISSUE THREAD

**Issue by Monteo** [Aviana/HealComm#21]
1x ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:1680: bad argument #5 to 'format' (string expected, got nil)
[C]: in function `format'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:1680: in function `?'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:2073: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2072>

Locals:
InCombatSkipped

**Comment by Aviana** [comment]
Should be fixed in latest release.
