### ISSUE TITLE
How do I download this?

### ISSUE THREAD

**Issue by TheSwartz** [Aviana/HealComm#24]
How do I download this?

I see where it says "DO NOT USE THE GREEN CLONE OR DOWNLOAD BUTTON. GET THE NEWEST RELEASE FROM THE RELEASE PAGE."

What does that mean?

Thanks!

**Comment by Aviana** [comment]
https://github.com/Aviana/HealComm/releases

**Comment by TheSwartz** [comment]
OK, sorry, I thought it just listed items marked as "source code" when I looked the first time. My bad. Thanks!
