### ISSUE TITLE
I just can't get this addon to work.

### ISSUE THREAD

**Issue by mazick** [Aviana/HealComm#25]
On login i get this with bug sack - I get other errors while in dungeons to. 

5x HealComm\HealComm-2003.nil.lua:76: attempt to index upvalue 'libCHC' (a nil value)
HealComm\HealComm-2003.nil.lua:76: in function `OnInitialize'
HealComm\HealComm-2003.nil.lua:276: in function <HealComm\HealComm.lua:274>

Locals:
self = <table> {
 HealComm_HealStopped = <function> defined @HealComm\HealComm.lua:181
 OnInitialize = <function> defined @HealComm\HealComm.lua:70
 PLAYER_ROLES_ASSIGNED = <function> defined @HealComm\HealComm.lua:117
 HealComm_ModifierChanged = <function> defined @HealComm\HealComm.lua:185
 CreateBars = <function> defined @HealComm\HealComm.lua:84
 UpdateFrame = <function> defined @HealComm\HealComm.lua:251
 version = 2003
 UNIT_PET = <function> defined @HealComm\HealComm.lua:96
 UpdateIncoming = <function> defined @HealComm\HealComm.lua:194
 HealComm_GUIDDisappeared = <function> defined @HealComm\HealComm.lua:189
 HealComm_HealUpdated = <function> defined @HealComm\HealComm.lua:177
 PLAYER_TARGET_CHANGED = <function> defined @HealComm\HealComm.lua:113
}
(*temporary) = nil
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 741
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 399
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this group."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 PawnUI_RefreshCompareScrollFrame = <function> defined @Pawn\PawnUI.lua:1482
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 VideoOptionsFrameDefaults = VideoOptionsFrameDefaults {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:602
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML\FloatingChatFrame.lua:2373
 BOOST2_WARRIOR_COLOSSUSSMASH = "Use |cFFFFFFFFColossus Smash|r.

|cFFFFFFFFColossus Smash|r increases your damage."
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 951
 _hack_prime_log = <function> defined @Questie\Modules\QuestieEventHandler.lua:1
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee ability with an increased range that consumes Combo Points."
 LibDBIcon10_BugSack = LibDBIcon10_BugSack {
 }
 StanceButton4FlyoutArrow = StanceButton4FlyoutArrow {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 DominosActionButton4Shine = DominosActionButto

**Comment by Aviana** [comment]
Well the upload got fucked up for the latest release. It should work now: https://github.com/Aviana/HealComm/releases
