### ISSUE TITLE
HOTS Show full heal over time

### ISSUE THREAD

**Issue by bradleyman88** [Aviana/HealComm#28]
HOTS show the full effect of their healing when they are cast, rather than the amount they will be healing on the next tick. Could cause some confusion if there isn't communication between raid healers.

**Comment by Aviana** [comment]
Yes i know there should be some basic options.

**Comment by bradleyman88** [comment]
Whats the command to open up those options?

**Comment by Aviana** [comment]
I mean there should be in the future.

**Comment by bradleyman88** [comment]
Ahh okay, lookin forward to it, other than that issue It's worked perfectly for me. Thanks for the work you've done!
