### ISSUE TITLE
'unitobj' (a nil value)

### ISSUE THREAD

**Issue by shagu** [Aviana/HealComm#3]
Hi,
there are LUA-Erros with the latest version:

`Interface\AddOns\HealComm\HealComm.lua:61: attempt to index global 'unitobj' (a nil value)
`

The error appears with all addons disabled beside HealComm.

I believe this is related to this commit: adb882ff151603a45f2583f49c3dcc317a2df4ef
where unitobj is removed but later on, unitobj is still be used.

https://github.com/Aviana/HealComm/commit/adb882ff151603a45f2583f49c3dcc317a2df4ef#diff-089364ee2d3a1d448371db28afb3b58cL47

**Comment by Aviana** [comment]
Fixed, updated & Stuff
